/**
 * Taxonomie complète des catégories de plats — miroir web de
 * dishrank/constants/categories.ts (les 260 entrées de DISH_CATEGORIES,
 * tous groupes confondus). Sert au picker « Catégories » d'un plat du menu
 * (colonne menu_items.category_slugs) : les slugs DOIVENT rester identiques à
 * ceux de l'app pour relier le plat aux notes de la communauté.
 *
 * ⚠️ Fichier GÉNÉRÉ (scratchpad/gen-categories.mjs). Ne pas éditer à la main :
 * régénérer depuis l'app après toute évolution de la taxonomie.
 */
export type CategoryGroup = 'dish' | 'street' | 'breakfast' | 'sweet' | 'drink' | 'cuisine' | 'diet';

export interface Category {
  slug: string;
  icon: string;
  group: CategoryGroup;
  name: string;
}

export const GROUP_ORDER: CategoryGroup[] = ["dish","street","breakfast","sweet","drink","cuisine","diet"];

export const GROUP_LABELS: Record<CategoryGroup, string> = {
  dish: 'Plats',
  street: 'Street food',
  breakfast: 'Petit-déjeuner',
  sweet: 'Sucré',
  drink: 'Boissons',
  cuisine: 'Cuisines du monde',
  diet: 'Régimes'
};

export const CATEGORIES: Category[] = [
  { slug: 'burger', icon: '🍔', group: 'dish', name: 'Burger' },
  { slug: 'pizza', icon: '🍕', group: 'dish', name: 'Pizza' },
  { slug: 'sushi', icon: '🍣', group: 'dish', name: 'Sushi' },
  { slug: 'pasta', icon: '🍝', group: 'dish', name: 'Pâtes' },
  { slug: 'meat', icon: '🍖', group: 'dish', name: 'Viande' },
  { slug: 'steak', icon: '🥩', group: 'dish', name: 'Steak' },
  { slug: 'chicken', icon: '🍗', group: 'dish', name: 'Poulet' },
  { slug: 'fish', icon: '🐟', group: 'dish', name: 'Poisson' },
  { slug: 'seafood', icon: '🦐', group: 'dish', name: 'Fruits de mer' },
  { slug: 'bbq', icon: '🍖', group: 'dish', name: 'BBQ' },
  { slug: 'sandwich', icon: '🥪', group: 'dish', name: 'Sandwich' },
  { slug: 'tacos', icon: '🌮', group: 'dish', name: 'Tacos' },
  { slug: 'burrito', icon: '🌯', group: 'dish', name: 'Burrito' },
  { slug: 'kebab', icon: '🥙', group: 'dish', name: 'Kebab' },
  { slug: 'falafel', icon: '🧆', group: 'dish', name: 'Falafel' },
  { slug: 'salad', icon: '🥗', group: 'dish', name: 'Salade' },
  { slug: 'bowl', icon: '🥣', group: 'dish', name: 'Bowls' },
  { slug: 'ramen', icon: '🍜', group: 'dish', name: 'Ramen' },
  { slug: 'pho', icon: '🍲', group: 'dish', name: 'Pho' },
  { slug: 'curry', icon: '🍛', group: 'dish', name: 'Curry' },
  { slug: 'dim-sum', icon: '🥟', group: 'dish', name: 'Dim Sum' },
  { slug: 'pad-thai', icon: '🍝', group: 'dish', name: 'Pad Thai' },
  { slug: 'bibimbap', icon: '🍚', group: 'dish', name: 'Bibimbap' },
  { slug: 'wok', icon: '🥘', group: 'dish', name: 'Wok' },
  { slug: 'teppanyaki', icon: '🔥', group: 'dish', name: 'Teppanyaki' },
  { slug: 'soup', icon: '🍲', group: 'dish', name: 'Soupe' },
  { slug: 'gratin', icon: '🧀', group: 'dish', name: 'Gratin' },
  { slug: 'risotto', icon: '🍚', group: 'dish', name: 'Risotto' },
  { slug: 'raclette', icon: '🫕', group: 'dish', name: 'Raclette' },
  { slug: 'fondue', icon: '🫕', group: 'dish', name: 'Fondue' },
  { slug: 'crepes', icon: '🥞', group: 'dish', name: 'Crêpes' },
  { slug: 'poutine', icon: '🍟', group: 'dish', name: 'Poutine' },
  { slug: 'couscous', icon: '🥘', group: 'dish', name: 'Couscous' },
  { slug: 'tajine', icon: '🫕', group: 'dish', name: 'Tajine' },
  { slug: 'tartare', icon: '🥩', group: 'dish', name: 'Tartare' },
  { slug: 'poke', icon: '🥗', group: 'dish', name: 'Poké' },
  { slug: 'ceviche', icon: '🐟', group: 'dish', name: 'Ceviche' },
  { slug: 'quiche', icon: '🥧', group: 'dish', name: 'Quiche' },
  { slug: 'lasagna', icon: '🍝', group: 'dish', name: 'Lasagne' },
  { slug: 'paella', icon: '🥘', group: 'dish', name: 'Paella' },
  { slug: 'gyoza', icon: '🥟', group: 'dish', name: 'Gyoza' },
  { slug: 'spring-rolls', icon: '🥢', group: 'dish', name: 'Nems' },
  { slug: 'shawarma', icon: '🥙', group: 'dish', name: 'Shawarma' },
  { slug: 'pierogi', icon: '🥟', group: 'dish', name: 'Pierogi' },
  { slug: 'dumpling', icon: '🥟', group: 'dish', name: 'Ravioli chinois' },
  { slug: 'rice', icon: '🍚', group: 'dish', name: 'Riz' },
  { slug: 'quenelle', icon: '🐟', group: 'dish', name: 'Quenelle' },
  { slug: 'cassoulet', icon: '🫘', group: 'dish', name: 'Cassoulet' },
  { slug: 'choucroute', icon: '🥬', group: 'dish', name: 'Choucroute' },
  { slug: 'galette', icon: '🫓', group: 'dish', name: 'Galette' },
  { slug: 'carpaccio', icon: '🥩', group: 'dish', name: 'Carpaccio' },
  { slug: 'duck', icon: '🦆', group: 'dish', name: 'Canard' },
  { slug: 'lamb', icon: '🐑', group: 'dish', name: 'Agneau' },
  { slug: 'beef', icon: '🥩', group: 'dish', name: 'Bœuf' },
  { slug: 'pork', icon: '🐷', group: 'dish', name: 'Porc' },
  { slug: 'veal', icon: '🥩', group: 'dish', name: 'Veau' },
  { slug: 'cote-de-boeuf', icon: '🥩', group: 'dish', name: 'Côte de bœuf' },
  { slug: 'sausage', icon: '🌭', group: 'dish', name: 'Saucisse' },
  { slug: 'meatballs', icon: '🍖', group: 'dish', name: 'Boulettes' },
  { slug: 'rabbit', icon: '🐰', group: 'dish', name: 'Lapin' },
  { slug: 'game', icon: '🦌', group: 'dish', name: 'Gibier' },
  { slug: 'liver', icon: '🥩', group: 'dish', name: 'Foie' },
  { slug: 'tripe', icon: '🫕', group: 'dish', name: 'Tripes' },
  { slug: 'boudin', icon: '🌭', group: 'dish', name: 'Boudin' },
  { slug: 'gnocchi', icon: '🥔', group: 'dish', name: 'Gnocchi' },
  { slug: 'sashimi', icon: '🍣', group: 'dish', name: 'Sashimi' },
  { slug: 'maki', icon: '🍙', group: 'dish', name: 'Maki' },
  { slug: 'tempura', icon: '🍤', group: 'dish', name: 'Tempura' },
  { slug: 'omelette', icon: '🍳', group: 'dish', name: 'Omelette' },
  { slug: 'escargot', icon: '🐌', group: 'dish', name: 'Escargot' },
  { slug: 'boeuf-bourguignon', icon: '🍷', group: 'dish', name: 'Bœuf bourguignon' },
  { slug: 'blanquette', icon: '🍲', group: 'dish', name: 'Blanquette' },
  { slug: 'pot-au-feu', icon: '🥘', group: 'dish', name: 'Pot-au-feu' },
  { slug: 'tartiflette', icon: '🧀', group: 'dish', name: 'Tartiflette' },
  { slug: 'magret', icon: '🥩', group: 'dish', name: 'Magret' },
  { slug: 'foie-gras', icon: '🍽️', group: 'dish', name: 'Foie gras' },
  { slug: 'osso-buco', icon: '🍖', group: 'dish', name: 'Osso Buco' },
  { slug: 'chili', icon: '🌶️', group: 'dish', name: 'Chili' },
  { slug: 'hummus', icon: '🫘', group: 'dish', name: 'Houmous' },
  { slug: 'moules-frites', icon: '🦪', group: 'dish', name: 'Moules-frites' },
  { slug: 'tarte', icon: '🥧', group: 'dish', name: 'Tarte salée' },
  { slug: 'croissant', icon: '🥐', group: 'dish', name: 'Croissant' },
  { slug: 'andouillette', icon: '🌭', group: 'dish', name: 'Andouillette' },
  { slug: 'salade-lyonnaise', icon: '🥗', group: 'dish', name: 'Salade lyonnaise' },
  { slug: 'tablier-sapeur', icon: '🍖', group: 'dish', name: 'Tablier de sapeur' },
  { slug: 'cervelle-canut', icon: '🧀', group: 'dish', name: 'Cervelle de canut' },
  { slug: 'bouillabaisse', icon: '🐟', group: 'dish', name: 'Bouillabaisse' },
  { slug: 'ratatouille', icon: '🍆', group: 'dish', name: 'Ratatouille' },
  { slug: 'confit-canard', icon: '🦆', group: 'dish', name: 'Confit de canard' },
  { slug: 'flammekueche', icon: '🫓', group: 'dish', name: 'Flammekueche' },
  { slug: 'aligot', icon: '🧀', group: 'dish', name: 'Aligot' },
  { slug: 'socca', icon: '🫓', group: 'dish', name: 'Socca' },
  { slug: 'pissaladiere', icon: '🍕', group: 'dish', name: 'Pissaladière' },
  { slug: 'gratin-dauphinois', icon: '🥔', group: 'dish', name: 'Gratin dauphinois' },
  { slug: 'tarte-tatin', icon: '🍎', group: 'dish', name: 'Tarte tatin' },
  { slug: 'creme-brulee', icon: '🍮', group: 'dish', name: 'Crème brûlée' },
  { slug: 'souffle', icon: '🍰', group: 'dish', name: 'Soufflé' },
  { slug: 'welsh', icon: '🧀', group: 'dish', name: 'Welsh' },
  { slug: 'carbonnade', icon: '🍺', group: 'dish', name: 'Carbonnade' },
  { slug: 'vitello-tonnato', icon: '🥩', group: 'dish', name: 'Vitello tonnato' },
  { slug: 'schnitzel', icon: '🥩', group: 'dish', name: 'Schnitzel' },
  { slug: 'moussaka', icon: '🍆', group: 'dish', name: 'Moussaka' },
  { slug: 'feijoada', icon: '🫘', group: 'dish', name: 'Feijoada' },
  { slug: 'croquetas', icon: '🍗', group: 'dish', name: 'Croquettes' },
  { slug: 'nasi-goreng', icon: '🍚', group: 'dish', name: 'Nasi Goreng' },
  { slug: 'rendang', icon: '🍛', group: 'dish', name: 'Rendang' },
  { slug: 'pho-bo', icon: '🍲', group: 'dish', name: 'Phở bò' },
  { slug: 'jerk-chicken', icon: '🍗', group: 'dish', name: 'Poulet jerk' },
  { slug: 'piri-piri', icon: '🌶️', group: 'dish', name: 'Piri-piri' },
  { slug: 'pierrade', icon: '🥩', group: 'dish', name: 'Pierrade' },
  { slug: 'tataki', icon: '🐟', group: 'dish', name: 'Tataki' },
  { slug: 'donburi', icon: '🍚', group: 'dish', name: 'Donburi' },
  { slug: 'yakitori', icon: '🍢', group: 'dish', name: 'Yakitori' },
  { slug: 'udon', icon: '🍜', group: 'dish', name: 'Udon' },
  { slug: 'okonomiyaki', icon: '🥞', group: 'dish', name: 'Okonomiyaki' },
  { slug: 'katsu', icon: '🍗', group: 'dish', name: 'Katsu' },
  { slug: 'fried-chicken', icon: '🍗', group: 'dish', name: 'Poulet frit' },
  { slug: 'wings', icon: '🍗', group: 'dish', name: 'Wings' },
  { slug: 'ribs', icon: '🍖', group: 'dish', name: 'Ribs' },
  { slug: 'pulled-pork', icon: '🐷', group: 'dish', name: 'Pulled Pork' },
  { slug: 'brisket', icon: '🥩', group: 'dish', name: 'Brisket' },
  { slug: 'smash-burger', icon: '🍔', group: 'dish', name: 'Smash Burger' },
  { slug: 'chirashi', icon: '🍣', group: 'dish', name: 'Chirashi' },
  { slug: 'california-roll', icon: '🍣', group: 'dish', name: 'California Roll' },
  { slug: 'onigiri', icon: '🍙', group: 'dish', name: 'Onigiri' },
  { slug: 'teriyaki', icon: '🍗', group: 'dish', name: 'Teriyaki' },
  { slug: 'tom-yum', icon: '🍲', group: 'dish', name: 'Tom Yum' },
  { slug: 'biryani', icon: '🍛', group: 'dish', name: 'Biryani' },
  { slug: 'tikka-masala', icon: '🍛', group: 'dish', name: 'Tikka Masala' },
  { slug: 'daal', icon: '🥘', group: 'dish', name: 'Daal' },
  { slug: 'noodles', icon: '🍜', group: 'dish', name: 'Nouilles' },
  { slug: 'fried-rice', icon: '🍳', group: 'dish', name: 'Riz sauté' },
  { slug: 'cordon-bleu', icon: '🍗', group: 'dish', name: 'Cordon Bleu' },
  { slug: 'entrecote', icon: '🥩', group: 'dish', name: 'Entrecôte' },
  { slug: 'filet-mignon', icon: '🥩', group: 'dish', name: 'Filet mignon' },
  { slug: 'souris-agneau', icon: '🐑', group: 'dish', name: 'Souris d\'agneau' },
  { slug: 'plancha', icon: '🔥', group: 'dish', name: 'Plancha' },
  { slug: 'cheese', icon: '🧀', group: 'dish', name: 'Fromage' },
  { slug: 'charcuterie', icon: '🥓', group: 'dish', name: 'Charcuterie' },
  { slug: 'fish-and-chips', icon: '🍟', group: 'dish', name: 'Fish & Chips' },
  { slug: 'steakhouse', icon: '🥩', group: 'dish', name: 'Steakhouse' },
  { slug: 'fast-food', icon: '🍔', group: 'dish', name: 'Fast Food' },
  { slug: 'breakfast', icon: '🥞', group: 'breakfast', name: 'Petit-déj' },
  { slug: 'brunch', icon: '🍳', group: 'breakfast', name: 'Brunch' },
  { slug: 'eggs', icon: '🥚', group: 'breakfast', name: 'Œufs' },
  { slug: 'pastry', icon: '🥐', group: 'breakfast', name: 'Viennoiserie' },
  { slug: 'acai', icon: '🫐', group: 'breakfast', name: 'Açaí Bowl' },
  { slug: 'granola', icon: '🥣', group: 'breakfast', name: 'Granola' },
  { slug: 'porridge', icon: '🥣', group: 'breakfast', name: 'Porridge' },
  { slug: 'dessert', icon: '🍰', group: 'sweet', name: 'Dessert' },
  { slug: 'ice-cream', icon: '🍦', group: 'sweet', name: 'Glace' },
  { slug: 'chocolate', icon: '🍫', group: 'sweet', name: 'Chocolat' },
  { slug: 'patisserie', icon: '🧁', group: 'sweet', name: 'Pâtisserie' },
  { slug: 'waffle', icon: '🧇', group: 'sweet', name: 'Gaufre' },
  { slug: 'cookie', icon: '🍪', group: 'sweet', name: 'Cookie' },
  { slug: 'donut', icon: '🍩', group: 'sweet', name: 'Donut' },
  { slug: 'tiramisu', icon: '🍰', group: 'sweet', name: 'Tiramisu' },
  { slug: 'cheesecake', icon: '🍰', group: 'sweet', name: 'Cheesecake' },
  { slug: 'pancake', icon: '🥞', group: 'sweet', name: 'Pancake' },
  { slug: 'mochi', icon: '🍡', group: 'sweet', name: 'Mochi' },
  { slug: 'coffee', icon: '☕', group: 'drink', name: 'Café' },
  { slug: 'tea', icon: '🍵', group: 'drink', name: 'Thé' },
  { slug: 'smoothie', icon: '🥤', group: 'drink', name: 'Smoothie' },
  { slug: 'bubble-tea', icon: '🧋', group: 'drink', name: 'Bubble Tea' },
  { slug: 'juice', icon: '🧃', group: 'drink', name: 'Jus' },
  { slug: 'cocktail', icon: '🍹', group: 'drink', name: 'Cocktail' },
  { slug: 'beer', icon: '🍺', group: 'drink', name: 'Bière' },
  { slug: 'wine', icon: '🍷', group: 'drink', name: 'Vin' },
  { slug: 'matcha', icon: '🍵', group: 'drink', name: 'Matcha' },
  { slug: 'milkshake', icon: '🥛', group: 'drink', name: 'Milkshake' },
  { slug: 'hot-chocolate', icon: '☕', group: 'drink', name: 'Chocolat chaud' },
  { slug: 'lemonade', icon: '🍋', group: 'drink', name: 'Limonade' },
  { slug: 'kombucha', icon: '🫧', group: 'drink', name: 'Kombucha' },
  { slug: 'cider', icon: '🍎', group: 'drink', name: 'Cidre' },
  { slug: 'sake', icon: '🍶', group: 'drink', name: 'Saké' },
  { slug: 'vegan', icon: '🌱', group: 'diet', name: 'Vegan' },
  { slug: 'vegetarian', icon: '🥬', group: 'diet', name: 'Végétarien' },
  { slug: 'gluten-free', icon: '🌾', group: 'diet', name: 'Sans gluten' },
  { slug: 'halal', icon: '☪️', group: 'diet', name: 'Halal' },
  { slug: 'kosher', icon: '✡️', group: 'diet', name: 'Casher' },
  { slug: 'organic', icon: '🌿', group: 'diet', name: 'Bio' },
  { slug: 'healthy', icon: '💚', group: 'diet', name: 'Healthy' },
  { slug: 'keto', icon: '🥑', group: 'diet', name: 'Keto' },
  { slug: 'french', icon: '🇫🇷', group: 'cuisine', name: 'Français' },
  { slug: 'italian', icon: '🇮🇹', group: 'cuisine', name: 'Italien' },
  { slug: 'japanese', icon: '🇯🇵', group: 'cuisine', name: 'Japonais' },
  { slug: 'chinese', icon: '🇨🇳', group: 'cuisine', name: 'Chinois' },
  { slug: 'thai', icon: '🇹🇭', group: 'cuisine', name: 'Thaï' },
  { slug: 'indian', icon: '🇮🇳', group: 'cuisine', name: 'Indien' },
  { slug: 'mexican', icon: '🇲🇽', group: 'cuisine', name: 'Mexicain' },
  { slug: 'lebanese', icon: '🇱🇧', group: 'cuisine', name: 'Libanais' },
  { slug: 'korean', icon: '🇰🇷', group: 'cuisine', name: 'Coréen' },
  { slug: 'vietnamese', icon: '🇻🇳', group: 'cuisine', name: 'Vietnamien' },
  { slug: 'turkish', icon: '🇹🇷', group: 'cuisine', name: 'Turc' },
  { slug: 'greek', icon: '🇬🇷', group: 'cuisine', name: 'Grec' },
  { slug: 'moroccan', icon: '🇲🇦', group: 'cuisine', name: 'Marocain' },
  { slug: 'ethiopian', icon: '🇪🇹', group: 'cuisine', name: 'Éthiopien' },
  { slug: 'peruvian', icon: '🇵🇪', group: 'cuisine', name: 'Péruvien' },
  { slug: 'american', icon: '🇺🇸', group: 'cuisine', name: 'Américain' },
  { slug: 'african', icon: '🌍', group: 'cuisine', name: 'Africain' },
  { slug: 'caribbean', icon: '🏝️', group: 'cuisine', name: 'Antillais' },
  { slug: 'spanish', icon: '🇪🇸', group: 'cuisine', name: 'Espagnol' },
  { slug: 'brazilian', icon: '🇧🇷', group: 'cuisine', name: 'Brésilien' },
  { slug: 'pakistani', icon: '🇵🇰', group: 'cuisine', name: 'Pakistanais' },
  { slug: 'filipino', icon: '🇵🇭', group: 'cuisine', name: 'Philippin' },
  { slug: 'sri-lankan', icon: '🇱🇰', group: 'cuisine', name: 'Sri-lankais' },
  { slug: 'canadian', icon: '🇨🇦', group: 'cuisine', name: 'Canadien' },
  { slug: 'portuguese', icon: '🇵🇹', group: 'cuisine', name: 'Portugais' },
  { slug: 'russian', icon: '🇷🇺', group: 'cuisine', name: 'Russe' },
  { slug: 'polish', icon: '🇵🇱', group: 'cuisine', name: 'Polonais' },
  { slug: 'indonesian', icon: '🇮🇩', group: 'cuisine', name: 'Indonésien' },
  { slug: 'tibetan', icon: '🏔️', group: 'cuisine', name: 'Tibétain' },
  { slug: 'algerian', icon: '🇩🇿', group: 'cuisine', name: 'Algérien' },
  { slug: 'tunisian', icon: '🇹🇳', group: 'cuisine', name: 'Tunisien' },
  { slug: 'israeli', icon: '🇮🇱', group: 'cuisine', name: 'Israélien' },
  { slug: 'argentinian', icon: '🇦🇷', group: 'cuisine', name: 'Argentin' },
  { slug: 'colombian', icon: '🇨🇴', group: 'cuisine', name: 'Colombien' },
  { slug: 'hawaiian', icon: '🌺', group: 'cuisine', name: 'Hawaïen' },
  { slug: 'malaysian', icon: '🇲🇾', group: 'cuisine', name: 'Malaisien' },
  { slug: 'iranian', icon: '🇮🇷', group: 'cuisine', name: 'Iranien' },
  { slug: 'jamaican', icon: '🇯🇲', group: 'cuisine', name: 'Jamaïcain' },
  { slug: 'senegalese', icon: '🇸🇳', group: 'cuisine', name: 'Sénégalais' },
  { slug: 'reunion', icon: '🇷🇪', group: 'cuisine', name: 'Réunionnais' },
  { slug: 'creole', icon: '🌴', group: 'cuisine', name: 'Créole' },
  { slug: 'asian', icon: '🥢', group: 'cuisine', name: 'Asiatique' },
  { slug: 'mediterranean', icon: '🫒', group: 'cuisine', name: 'Méditerranéen' },
  { slug: 'cajun', icon: '🌶️', group: 'cuisine', name: 'Cajun' },
  { slug: 'tex-mex', icon: '🌮', group: 'cuisine', name: 'Tex-Mex' },
  { slug: 'sichuan', icon: '🌶️', group: 'cuisine', name: 'Sichuan' },
  { slug: 'cantonese', icon: '🥟', group: 'cuisine', name: 'Cantonais' },
  { slug: 'german', icon: '🇩🇪', group: 'cuisine', name: 'Allemand' },
  { slug: 'british', icon: '🇬🇧', group: 'cuisine', name: 'Britannique' },
  { slug: 'egyptian', icon: '🇪🇬', group: 'cuisine', name: 'Égyptien' },
  { slug: 'cambodian', icon: '🇰🇭', group: 'cuisine', name: 'Cambodgien' },
  { slug: 'laotian', icon: '🇱🇦', group: 'cuisine', name: 'Laotien' },
  { slug: 'nepali', icon: '🇳🇵', group: 'cuisine', name: 'Népalais' },
  { slug: 'kurdish', icon: '☀️', group: 'cuisine', name: 'Kurde' },
  { slug: 'afghan', icon: '🇦🇫', group: 'cuisine', name: 'Afghan' },
  { slug: 'congolese', icon: '🇨🇩', group: 'cuisine', name: 'Congolais' },
  { slug: 'ivorian', icon: '🇨🇮', group: 'cuisine', name: 'Ivoirien' },
  { slug: 'street-food', icon: '🛒', group: 'street', name: 'Street Food' },
  { slug: 'fries', icon: '🍟', group: 'street', name: 'Frites' },
  { slug: 'nuggets', icon: '🍗', group: 'street', name: 'Nuggets' },
  { slug: 'hot-dog', icon: '🌭', group: 'street', name: 'Hot Dog' },
  { slug: 'empanadas', icon: '🥟', group: 'street', name: 'Empanadas' },
  { slug: 'naan', icon: '🫓', group: 'street', name: 'Naan' },
  { slug: 'tapas', icon: '🫒', group: 'street', name: 'Tapas' },
  { slug: 'samosa', icon: '🔺', group: 'street', name: 'Samosa' },
  { slug: 'banh-mi', icon: '🥖', group: 'street', name: 'Bánh Mì' },
  { slug: 'gyros', icon: '🥙', group: 'street', name: 'Gyros' },
  { slug: 'arepas', icon: '🫓', group: 'street', name: 'Arepas' },
  { slug: 'croque-monsieur', icon: '🧀', group: 'street', name: 'Croque-monsieur' },
  { slug: 'panini', icon: '🥖', group: 'street', name: 'Panini' },
  { slug: 'pretzel', icon: '🥨', group: 'street', name: 'Bretzel' },
  { slug: 'churros', icon: '🍩', group: 'street', name: 'Churros' },
  { slug: 'bao', icon: '🥟', group: 'street', name: 'Bao' },
  { slug: 'bruschetta', icon: '🍞', group: 'street', name: 'Bruschetta' },
  { slug: 'wrap', icon: '🌯', group: 'street', name: 'Wrap' },
  { slug: 'corn-dog', icon: '🌽', group: 'street', name: 'Corn Dog' },
  { slug: 'takoyaki', icon: '🐙', group: 'street', name: 'Takoyaki' },
];

export const CATEGORY_BY_SLUG = new Map(CATEGORIES.map((c) => [c.slug, c]));
export const CATEGORY_SLUGS = new Set(CATEGORIES.map((c) => c.slug));

function normalize(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

/** Recherche par nom OU slug, insensible aux accents/casse, hors déjà choisis. */
export function searchCategories(query: string, exclude: Set<string>): Category[] {
  const q = normalize(query);
  return CATEGORIES.filter((c) => {
    if (exclude.has(c.slug)) return false;
    if (!q) return true;
    return normalize(c.name).includes(q) || c.slug.includes(q);
  });
}
