/**
 * Taxonomie des « types d'établissement » de l'espace pro — miroir web de la
 * taxonomie COMPLÈTE de l'app (dishrank/constants/categories.ts), tous les
 * groupes sauf 'diet' : cuisine, plat, street, sweet, drink, breakfast. Les
 * slugs DOIVENT rester identiques à ceux stockés dans `restaurants.cuisines`
 * (text[]) pour que la fiche web et l'app parlent le même vocabulaire.
 *
 * `icon` = l'emoji exact de l'app. Les emoji drapeau sont rendus correctement
 * grâce à <FlagPolyfill/> (police « Twemoji Country Flags »), monté sur /pro.
 *
 * Généré depuis l'app — voir scratchpad/gen_cuisines.js. Ne pas éditer à la main.
 */
export interface Cuisine {
  slug: string;
  icon: string;
  name: string;
}

export const CUISINES: Cuisine[] = [
  { slug: 'french', icon: '🇫🇷', name: 'Français' },
  { slug: 'italian', icon: '🇮🇹', name: 'Italien' },
  { slug: 'japanese', icon: '🇯🇵', name: 'Japonais' },
  { slug: 'chinese', icon: '🇨🇳', name: 'Chinois' },
  { slug: 'thai', icon: '🇹🇭', name: 'Thaï' },
  { slug: 'indian', icon: '🇮🇳', name: 'Indien' },
  { slug: 'mexican', icon: '🇲🇽', name: 'Mexicain' },
  { slug: 'lebanese', icon: '🇱🇧', name: 'Libanais' },
  { slug: 'korean', icon: '🇰🇷', name: 'Coréen' },
  { slug: 'vietnamese', icon: '🇻🇳', name: 'Vietnamien' },
  { slug: 'turkish', icon: '🇹🇷', name: 'Turc' },
  { slug: 'greek', icon: '🇬🇷', name: 'Grec' },
  { slug: 'moroccan', icon: '🇲🇦', name: 'Marocain' },
  { slug: 'ethiopian', icon: '🇪🇹', name: 'Éthiopien' },
  { slug: 'peruvian', icon: '🇵🇪', name: 'Péruvien' },
  { slug: 'american', icon: '🇺🇸', name: 'Américain' },
  { slug: 'african', icon: '🌍', name: 'Africain' },
  { slug: 'caribbean', icon: '🏝️', name: 'Antillais' },
  { slug: 'spanish', icon: '🇪🇸', name: 'Espagnol' },
  { slug: 'brazilian', icon: '🇧🇷', name: 'Brésilien' },
  { slug: 'pakistani', icon: '🇵🇰', name: 'Pakistanais' },
  { slug: 'filipino', icon: '🇵🇭', name: 'Philippin' },
  { slug: 'sri-lankan', icon: '🇱🇰', name: 'Sri-lankais' },
  { slug: 'canadian', icon: '🇨🇦', name: 'Canadien' },
  { slug: 'portuguese', icon: '🇵🇹', name: 'Portugais' },
  { slug: 'russian', icon: '🇷🇺', name: 'Russe' },
  { slug: 'polish', icon: '🇵🇱', name: 'Polonais' },
  { slug: 'indonesian', icon: '🇮🇩', name: 'Indonésien' },
  { slug: 'tibetan', icon: '🏔️', name: 'Tibétain' },
  { slug: 'algerian', icon: '🇩🇿', name: 'Algérien' },
  { slug: 'tunisian', icon: '🇹🇳', name: 'Tunisien' },
  { slug: 'israeli', icon: '🇮🇱', name: 'Israélien' },
  { slug: 'argentinian', icon: '🇦🇷', name: 'Argentin' },
  { slug: 'colombian', icon: '🇨🇴', name: 'Colombien' },
  { slug: 'hawaiian', icon: '🌺', name: 'Hawaïen' },
  { slug: 'malaysian', icon: '🇲🇾', name: 'Malaisien' },
  { slug: 'iranian', icon: '🇮🇷', name: 'Iranien' },
  { slug: 'jamaican', icon: '🇯🇲', name: 'Jamaïcain' },
  { slug: 'senegalese', icon: '🇸🇳', name: 'Sénégalais' },
  { slug: 'reunion', icon: '🇷🇪', name: 'Réunionnais' },
  { slug: 'creole', icon: '🌴', name: 'Créole' },
  { slug: 'asian', icon: '🥢', name: 'Asiatique' },
  { slug: 'mediterranean', icon: '🫒', name: 'Méditerranéen' },
  { slug: 'cajun', icon: '🌶️', name: 'Cajun' },
  { slug: 'tex-mex', icon: '🌮', name: 'Tex-Mex' },
  { slug: 'sichuan', icon: '🌶️', name: 'Sichuan' },
  { slug: 'cantonese', icon: '🥟', name: 'Cantonais' },
  { slug: 'german', icon: '🇩🇪', name: 'Allemand' },
  { slug: 'british', icon: '🇬🇧', name: 'Britannique' },
  { slug: 'egyptian', icon: '🇪🇬', name: 'Égyptien' },
  { slug: 'cambodian', icon: '🇰🇭', name: 'Cambodgien' },
  { slug: 'laotian', icon: '🇱🇦', name: 'Laotien' },
  { slug: 'nepali', icon: '🇳🇵', name: 'Népalais' },
  { slug: 'kurdish', icon: '☀️', name: 'Kurde' },
  { slug: 'afghan', icon: '🇦🇫', name: 'Afghan' },
  { slug: 'congolese', icon: '🇨🇩', name: 'Congolais' },
  { slug: 'ivorian', icon: '🇨🇮', name: 'Ivoirien' },
  { slug: 'armenian', icon: '🇦🇲', name: 'Arménien' },
  { slug: 'syrian', icon: '🇸🇾', name: 'Syrien' },
  { slug: 'taiwanese', icon: '🇹🇼', name: 'Taïwanais' },
  { slug: 'maghrebi', icon: '🌍', name: 'Maghrébin' },
  { slug: 'corsican', icon: '🏝️', name: 'Corse' },
  { slug: 'bistro', icon: '🍴', name: 'Bistrot' },
  { slug: 'brasserie', icon: '🍺', name: 'Brasserie' },
  { slug: 'bouchon', icon: '🍷', name: 'Bouchon lyonnais' },
  { slug: 'gastronomique', icon: '⭐', name: 'Gastronomique' },
  { slug: 'buffet', icon: '🍽️', name: 'Buffet' },
  { slug: 'food-truck', icon: '🚚', name: 'Food truck' },
  { slug: 'wine-bar', icon: '🍷', name: 'Bar à vin' },
  { slug: 'coffee-shop', icon: '☕', name: 'Coffee shop' },
  { slug: 'tea-room', icon: '🫖', name: 'Salon de thé' },
  { slug: 'creperie', icon: '🥞', name: 'Crêperie' },
  { slug: 'pizzeria', icon: '🍕', name: 'Pizzeria' },
  { slug: 'snack', icon: '🥪', name: 'Snack' },
  { slug: 'burger', icon: '🍔', name: 'Burger' },
  { slug: 'pizza', icon: '🍕', name: 'Pizza' },
  { slug: 'sushi', icon: '🍣', name: 'Sushi' },
  { slug: 'pasta', icon: '🍝', name: 'Pâtes' },
  { slug: 'meat', icon: '🍖', name: 'Viande' },
  { slug: 'steak', icon: '🥩', name: 'Steak' },
  { slug: 'chicken', icon: '🍗', name: 'Poulet' },
  { slug: 'fish', icon: '🐟', name: 'Poisson' },
  { slug: 'seafood', icon: '🦐', name: 'Fruits de mer' },
  { slug: 'bbq', icon: '🍖', name: 'BBQ' },
  { slug: 'sandwich', icon: '🥪', name: 'Sandwich' },
  { slug: 'tacos', icon: '🌮', name: 'Tacos' },
  { slug: 'burrito', icon: '🌯', name: 'Burrito' },
  { slug: 'kebab', icon: '🥙', name: 'Kebab' },
  { slug: 'falafel', icon: '🧆', name: 'Falafel' },
  { slug: 'salad', icon: '🥗', name: 'Salade' },
  { slug: 'bowl', icon: '🥣', name: 'Bowls' },
  { slug: 'ramen', icon: '🍜', name: 'Ramen' },
  { slug: 'pho', icon: '🍲', name: 'Pho' },
  { slug: 'curry', icon: '🍛', name: 'Curry' },
  { slug: 'dim-sum', icon: '🥟', name: 'Dim Sum' },
  { slug: 'pad-thai', icon: '🍝', name: 'Pad Thai' },
  { slug: 'bibimbap', icon: '🍚', name: 'Bibimbap' },
  { slug: 'wok', icon: '🥘', name: 'Wok' },
  { slug: 'teppanyaki', icon: '🔥', name: 'Teppanyaki' },
  { slug: 'soup', icon: '🍲', name: 'Soupe' },
  { slug: 'gratin', icon: '🧀', name: 'Gratin' },
  { slug: 'risotto', icon: '🍚', name: 'Risotto' },
  { slug: 'raclette', icon: '🫕', name: 'Raclette' },
  { slug: 'fondue', icon: '🫕', name: 'Fondue' },
  { slug: 'crepes', icon: '🥞', name: 'Crêpes' },
  { slug: 'poutine', icon: '🍟', name: 'Poutine' },
  { slug: 'couscous', icon: '🥘', name: 'Couscous' },
  { slug: 'tajine', icon: '🫕', name: 'Tajine' },
  { slug: 'tartare', icon: '🥩', name: 'Tartare' },
  { slug: 'poke', icon: '🥗', name: 'Poké' },
  { slug: 'ceviche', icon: '🐟', name: 'Ceviche' },
  { slug: 'quiche', icon: '🥧', name: 'Quiche' },
  { slug: 'lasagna', icon: '🍝', name: 'Lasagne' },
  { slug: 'paella', icon: '🥘', name: 'Paella' },
  { slug: 'gyoza', icon: '🥟', name: 'Gyoza' },
  { slug: 'spring-rolls', icon: '🥢', name: 'Nems' },
  { slug: 'shawarma', icon: '🥙', name: 'Shawarma' },
  { slug: 'pierogi', icon: '🥟', name: 'Pierogi' },
  { slug: 'dumpling', icon: '🥟', name: 'Ravioli chinois' },
  { slug: 'rice', icon: '🍚', name: 'Riz' },
  { slug: 'quenelle', icon: '🐟', name: 'Quenelle' },
  { slug: 'cassoulet', icon: '🫘', name: 'Cassoulet' },
  { slug: 'choucroute', icon: '🥬', name: 'Choucroute' },
  { slug: 'galette', icon: '🫓', name: 'Galette' },
  { slug: 'carpaccio', icon: '🥩', name: 'Carpaccio' },
  { slug: 'duck', icon: '🦆', name: 'Canard' },
  { slug: 'lamb', icon: '🐑', name: 'Agneau' },
  { slug: 'beef', icon: '🥩', name: 'Bœuf' },
  { slug: 'pork', icon: '🐷', name: 'Porc' },
  { slug: 'veal', icon: '🥩', name: 'Veau' },
  { slug: 'cote-de-boeuf', icon: '🥩', name: 'Côte de bœuf' },
  { slug: 'sausage', icon: '🌭', name: 'Saucisse' },
  { slug: 'meatballs', icon: '🍖', name: 'Boulettes' },
  { slug: 'rabbit', icon: '🐰', name: 'Lapin' },
  { slug: 'game', icon: '🦌', name: 'Gibier' },
  { slug: 'liver', icon: '🥩', name: 'Foie' },
  { slug: 'tripe', icon: '🫕', name: 'Tripes' },
  { slug: 'boudin', icon: '🌭', name: 'Boudin' },
  { slug: 'gnocchi', icon: '🥔', name: 'Gnocchi' },
  { slug: 'sashimi', icon: '🍣', name: 'Sashimi' },
  { slug: 'maki', icon: '🍙', name: 'Maki' },
  { slug: 'tempura', icon: '🍤', name: 'Tempura' },
  { slug: 'omelette', icon: '🍳', name: 'Omelette' },
  { slug: 'escargot', icon: '🐌', name: 'Escargot' },
  { slug: 'boeuf-bourguignon', icon: '🍷', name: 'Bœuf bourguignon' },
  { slug: 'blanquette', icon: '🍲', name: 'Blanquette' },
  { slug: 'pot-au-feu', icon: '🥘', name: 'Pot-au-feu' },
  { slug: 'tartiflette', icon: '🧀', name: 'Tartiflette' },
  { slug: 'magret', icon: '🥩', name: 'Magret' },
  { slug: 'foie-gras', icon: '🍽️', name: 'Foie gras' },
  { slug: 'osso-buco', icon: '🍖', name: 'Osso Buco' },
  { slug: 'chili', icon: '🌶️', name: 'Chili' },
  { slug: 'hummus', icon: '🫘', name: 'Houmous' },
  { slug: 'moules-frites', icon: '🦪', name: 'Moules-frites' },
  { slug: 'tarte', icon: '🥧', name: 'Tarte salée' },
  { slug: 'croissant', icon: '🥐', name: 'Croissant' },
  { slug: 'andouillette', icon: '🌭', name: 'Andouillette' },
  { slug: 'salade-lyonnaise', icon: '🥗', name: 'Salade lyonnaise' },
  { slug: 'tablier-sapeur', icon: '🍖', name: 'Tablier de sapeur' },
  { slug: 'cervelle-canut', icon: '🧀', name: 'Cervelle de canut' },
  { slug: 'bouillabaisse', icon: '🐟', name: 'Bouillabaisse' },
  { slug: 'ratatouille', icon: '🍆', name: 'Ratatouille' },
  { slug: 'confit-canard', icon: '🦆', name: 'Confit de canard' },
  { slug: 'flammekueche', icon: '🫓', name: 'Flammekueche' },
  { slug: 'aligot', icon: '🧀', name: 'Aligot' },
  { slug: 'socca', icon: '🫓', name: 'Socca' },
  { slug: 'pissaladiere', icon: '🍕', name: 'Pissaladière' },
  { slug: 'gratin-dauphinois', icon: '🥔', name: 'Gratin dauphinois' },
  { slug: 'tarte-tatin', icon: '🍎', name: 'Tarte tatin' },
  { slug: 'creme-brulee', icon: '🍮', name: 'Crème brûlée' },
  { slug: 'souffle', icon: '🍰', name: 'Soufflé' },
  { slug: 'welsh', icon: '🧀', name: 'Welsh' },
  { slug: 'carbonnade', icon: '🍺', name: 'Carbonnade' },
  { slug: 'vitello-tonnato', icon: '🥩', name: 'Vitello tonnato' },
  { slug: 'schnitzel', icon: '🥩', name: 'Schnitzel' },
  { slug: 'moussaka', icon: '🍆', name: 'Moussaka' },
  { slug: 'feijoada', icon: '🫘', name: 'Feijoada' },
  { slug: 'croquetas', icon: '🍗', name: 'Croquettes' },
  { slug: 'nasi-goreng', icon: '🍚', name: 'Nasi Goreng' },
  { slug: 'rendang', icon: '🍛', name: 'Rendang' },
  { slug: 'pho-bo', icon: '🍲', name: 'Phở bò' },
  { slug: 'jerk-chicken', icon: '🍗', name: 'Poulet jerk' },
  { slug: 'piri-piri', icon: '🌶️', name: 'Piri-piri' },
  { slug: 'pierrade', icon: '🥩', name: 'Pierrade' },
  { slug: 'tataki', icon: '🐟', name: 'Tataki' },
  { slug: 'donburi', icon: '🍚', name: 'Donburi' },
  { slug: 'yakitori', icon: '🍢', name: 'Yakitori' },
  { slug: 'udon', icon: '🍜', name: 'Udon' },
  { slug: 'okonomiyaki', icon: '🥞', name: 'Okonomiyaki' },
  { slug: 'katsu', icon: '🍗', name: 'Katsu' },
  { slug: 'fried-chicken', icon: '🍗', name: 'Poulet frit' },
  { slug: 'wings', icon: '🍗', name: 'Wings' },
  { slug: 'ribs', icon: '🍖', name: 'Ribs' },
  { slug: 'pulled-pork', icon: '🐷', name: 'Pulled Pork' },
  { slug: 'brisket', icon: '🥩', name: 'Brisket' },
  { slug: 'smash-burger', icon: '🍔', name: 'Smash Burger' },
  { slug: 'chirashi', icon: '🍣', name: 'Chirashi' },
  { slug: 'california-roll', icon: '🍣', name: 'California Roll' },
  { slug: 'onigiri', icon: '🍙', name: 'Onigiri' },
  { slug: 'teriyaki', icon: '🍗', name: 'Teriyaki' },
  { slug: 'tom-yum', icon: '🍲', name: 'Tom Yum' },
  { slug: 'biryani', icon: '🍛', name: 'Biryani' },
  { slug: 'tikka-masala', icon: '🍛', name: 'Tikka Masala' },
  { slug: 'daal', icon: '🥘', name: 'Daal' },
  { slug: 'noodles', icon: '🍜', name: 'Nouilles' },
  { slug: 'fried-rice', icon: '🍳', name: 'Riz sauté' },
  { slug: 'cordon-bleu', icon: '🍗', name: 'Cordon Bleu' },
  { slug: 'entrecote', icon: '🥩', name: 'Entrecôte' },
  { slug: 'filet-mignon', icon: '🥩', name: 'Filet mignon' },
  { slug: 'souris-agneau', icon: '🐑', name: 'Souris d\'agneau' },
  { slug: 'plancha', icon: '🔥', name: 'Plancha' },
  { slug: 'cheese', icon: '🧀', name: 'Fromage' },
  { slug: 'charcuterie', icon: '🥓', name: 'Charcuterie' },
  { slug: 'fish-and-chips', icon: '🍟', name: 'Fish & Chips' },
  { slug: 'steakhouse', icon: '🥩', name: 'Steakhouse' },
  { slug: 'fast-food', icon: '🍔', name: 'Fast Food' },
  { slug: 'street-food', icon: '🛒', name: 'Street Food' },
  { slug: 'fries', icon: '🍟', name: 'Frites' },
  { slug: 'nuggets', icon: '🍗', name: 'Nuggets' },
  { slug: 'hot-dog', icon: '🌭', name: 'Hot Dog' },
  { slug: 'empanadas', icon: '🥟', name: 'Empanadas' },
  { slug: 'naan', icon: '🫓', name: 'Naan' },
  { slug: 'tapas', icon: '🫒', name: 'Tapas' },
  { slug: 'samosa', icon: '🔺', name: 'Samosa' },
  { slug: 'banh-mi', icon: '🥖', name: 'Bánh Mì' },
  { slug: 'gyros', icon: '🥙', name: 'Gyros' },
  { slug: 'arepas', icon: '🫓', name: 'Arepas' },
  { slug: 'croque-monsieur', icon: '🧀', name: 'Croque-monsieur' },
  { slug: 'panini', icon: '🥖', name: 'Panini' },
  { slug: 'pretzel', icon: '🥨', name: 'Bretzel' },
  { slug: 'churros', icon: '🍩', name: 'Churros' },
  { slug: 'bao', icon: '🥟', name: 'Bao' },
  { slug: 'bruschetta', icon: '🍞', name: 'Bruschetta' },
  { slug: 'wrap', icon: '🌯', name: 'Wrap' },
  { slug: 'corn-dog', icon: '🌽', name: 'Corn Dog' },
  { slug: 'takoyaki', icon: '🐙', name: 'Takoyaki' },
  { slug: 'dessert', icon: '🍰', name: 'Dessert' },
  { slug: 'ice-cream', icon: '🍦', name: 'Glace' },
  { slug: 'chocolate', icon: '🍫', name: 'Chocolat' },
  { slug: 'patisserie', icon: '🧁', name: 'Pâtisserie' },
  { slug: 'waffle', icon: '🧇', name: 'Gaufre' },
  { slug: 'cookie', icon: '🍪', name: 'Cookie' },
  { slug: 'donut', icon: '🍩', name: 'Donut' },
  { slug: 'tiramisu', icon: '🍰', name: 'Tiramisu' },
  { slug: 'cheesecake', icon: '🍰', name: 'Cheesecake' },
  { slug: 'pancake', icon: '🥞', name: 'Pancake' },
  { slug: 'mochi', icon: '🍡', name: 'Mochi' },
  { slug: 'coffee', icon: '☕', name: 'Café' },
  { slug: 'tea', icon: '🍵', name: 'Thé' },
  { slug: 'smoothie', icon: '🥤', name: 'Smoothie' },
  { slug: 'bubble-tea', icon: '🧋', name: 'Bubble Tea' },
  { slug: 'juice', icon: '🧃', name: 'Jus' },
  { slug: 'cocktail', icon: '🍹', name: 'Cocktail' },
  { slug: 'beer', icon: '🍺', name: 'Bière' },
  { slug: 'wine', icon: '🍷', name: 'Vin' },
  { slug: 'matcha', icon: '🍵', name: 'Matcha' },
  { slug: 'milkshake', icon: '🥛', name: 'Milkshake' },
  { slug: 'hot-chocolate', icon: '☕', name: 'Chocolat chaud' },
  { slug: 'lemonade', icon: '🍋', name: 'Limonade' },
  { slug: 'kombucha', icon: '🫧', name: 'Kombucha' },
  { slug: 'cider', icon: '🍎', name: 'Cidre' },
  { slug: 'sake', icon: '🍶', name: 'Saké' },
  { slug: 'breakfast', icon: '🥞', name: 'Petit-déj' },
  { slug: 'brunch', icon: '🍳', name: 'Brunch' },
  { slug: 'eggs', icon: '🥚', name: 'Œufs' },
  { slug: 'pastry', icon: '🥐', name: 'Viennoiserie' },
  { slug: 'acai', icon: '🫐', name: 'Açaí Bowl' },
  { slug: 'granola', icon: '🥣', name: 'Granola' },
  { slug: 'porridge', icon: '🥣', name: 'Porridge' },
];

export const CUISINE_BY_SLUG = new Map(CUISINES.map((c) => [c.slug, c]));

/** Slugs valides — pour filtrer côté serveur ce que le formulaire envoie. */
export const CUISINE_SLUGS = new Set(CUISINES.map((c) => c.slug));

/** Retire les accents/casse pour une recherche tolérante. */
function normalize(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim();
}

/** Recherche par nom OU slug, insensible aux accents/casse. */
export function searchCuisines(query: string, exclude: Set<string>): Cuisine[] {
  const q = normalize(query);
  return CUISINES.filter((c) => {
    if (exclude.has(c.slug)) return false;
    if (!q) return true;
    return normalize(c.name).includes(q) || c.slug.includes(q);
  });
}
